### PR TITLE
Pro7

### PR DESCRIPTION
**Pull request by jpc0**
Update to ProPresenter 7 API,

In line 916 for some reason if you pass presentationName it fails.

### CODE REVIEW

**Comment by josephdadams** [comment]
Should we include an option for the user to select Pro6 or Pro7? Or just break Pro6 support at this point?

**Comment by jdonor** [comment]
> Should we include an option for the user to select Pro6 or Pro7? Or just break Pro6 support at this point?

I'd say you could break Pro6 support, just release it as a new version and maybe still keep the download link for the old one active in case some users are still on Pro6.

**Comment by davecalkins** [comment]
Was curious about getting the image viewer working with Pro7 and dug around a little.  I applied the changes from @jdonor to my local repo and noticed in bridge.html, when webSocketRemote gets "authenticate" for message.action, its getting the below error.

`message={"controller":0,"authenticated":0,"error":"Remote application protocol out of date. Update application","majorVersion":7,"minorVersion":5,"protocol":701,"action":"authenticate"}
`

I'm testing with ProPresenter 7.5.1.  In setupRemoteSocket(), the protocol argument was "700".  I changed it to "701" and after doing that, the authenticate message comes back as follows.

`message={"controller":1,"authenticated":1,"error":"","majorVersion":7,"minorVersion":5,"protocol":701,"action":"authenticate"}
`

However, now even the text view doesn't work.  So maybe there are other changes in the protocol.

**Comment by jdonor** [comment]
I know there have been a decent amount of bugs in 7.5 in general, I wouldn't be surprised if those issues are due to a bug in the protocol.

**Comment by davecalkins** [comment]
If I do not apply the changes in this PR, leaving it at the Pro6 values, the text still works and the authenticate doesn't complain.  So it appears Pro7 supports a Pro6 client.  With that in place, I noticed the following.

As I switch slides in Pro7, I am getting the "presentationTriggerIndex" message from the remote socket in bridge.html.  This calls findPresentation() which fails to find anything.  It doesn't find anything because the Presentations array is empty.  This array is populated in response to the "playlistRequestAll" message from the remote socket which is never happening.

Not sure why but I'm never receiving the "playlistRequestAll" message which I think explains at least its not loading presentations and then can't find anything when you switch slides.

**Comment by davecalkins** [comment]
Here's what I'm seeing.  When ProPresenterAPI_AddPlaylistsToArray() is called (as a result of receiving the "playlistRequestAll" message from the remote socket) the object it receives is structured differently than what the code is expecting.  

The code is expecting an object which has a list of playlists, where each playlist has a list of presentations.  When I test it in our environment, its actually a multi-level collection.  So the playlistObj has groups which can contain other groups and playlists which can contain playlist items.  Perhaps this is a change with Pro7, it's a tree of groups and playlists and eventually items, rather than a simpler list of playlists which have lists of items.

For example, I logged out the below.

https://gist.github.com/davecalkins/0ce13ec438c1cdfc870cd5948dabaed0

**Pull request closed without merging**
